Inteon/moadeli/tip bump
InteonCo/Polygeist pull request #5
Opened 2022-02-08 09:06 UTC by mmoadeli

The PR has all changes required to make Polygeist process input SYCL kernel. There are a number of commits which are here as work around. They are going to be addressed.

2022-02-08 11:46 UTC, joeatodd approved these changes
LGTM aside from possible violation of requirements of `cl::ConsumeAfter` and a few minor formatting issues.

2022-02-08 11:46 UTC, joeatodd commented on tools/mlir-clang/Lib/clang-mlir.cc
> +llvm::SmallVector<const ArgStringList *, 4> CommandList;
Indentation ->

2022-02-08 11:46 UTC, joeatodd commented on tools/mlir-clang/Lib/clang-mlir.cc
> +                                                  Diags);
Indentation

2022-02-08 11:46 UTC, joeatodd commented on tools/mlir-clang/CMakeLists.txt
> +Message(STATUS "Mahmoud clang dir: ${CLANG_DIR}")
Should this debug statement be tidied away?

2022-02-08 11:46 UTC, joeatodd commented on tools/mlir-clang/mlir-clang.cc
> +
I don't know much about the LLVM CommandLine library - as I was reading the docs for `cl::ConsumeAfter` below, I [found](https://llvm.org/docs/CommandLine.html#the-cl-consumeafter-modifier) the following:

> There are several limitations to when cl::ConsumeAfter options can be specified. For example, only one cl::ConsumeAfter can be specified per program, there must be at least one [positional argument](https://llvm.org/docs/CommandLine.html#positional-argument) specified, **there must not be any [cl::list](https://llvm.org/docs/CommandLine.html#cl-list) positional arguments**, and the cl::ConsumeAfter option should be a [cl::list](https://llvm.org/docs/CommandLine.html#cl-list) option.

I think having `inputFileName` defined as a `cl::list` violates this?

2022-02-08 13:02 UTC, mmoadeli commented on tools/mlir-clang/mlir-clang.cc
> +
Thanks. That makes sense. I create  a task to have this investigated.

2022-02-08 13:34 UTC, mmoadeli commented on tools/mlir-clang/mlir-clang.cc
> +
https://jira.office.codeplay.com/browse/II-187

2022-02-08 15:51 UTC, frengels requested changes
Just minor style nitpicks, and for chasing things down in the future

2022-02-08 15:51 UTC, frengels commented on tools/mlir-clang/Lib/clang-mlir.cc
> +
should commented out code get removed?

2022-02-08 15:51 UTC, frengels commented on tools/mlir-clang/mlir-clang.cc
> +//      module->dump();
could a comment be added explaining why these are commented out and linking to the JIRA ticket

2022-02-08 15:51 UTC, frengels commented on tools/mlir-clang/mlir-clang.cc
> +      // }
same comment and JIRA ticket here

2022-02-08 17:08 UTC, mmoadeli commented on tools/mlir-clang/mlir-clang.cc
> +//      module->dump();
There is a ticket created for this and have the link to the associated commit.

2022-02-08 17:09 UTC, mmoadeli commented on tools/mlir-clang/Lib/clang-mlir.cc
> +
I found this widely used when debugging. I'd prefer keeping it.

2022-02-22 03:56 UTC, breanna-devore-mcdonald requested changes
The CI tests are failing- should be fixed before merging?

2022-02-22 03:56 UTC, breanna-devore-mcdonald commented on tools/mlir-clang/mlir-clang.cc
> +//      module->dump();
@mmoadeli can that ticket link be added as a comment in the code?

2022-02-22 16:25 UTC, breanna-devore-mcdonald commented on tools/mlir-clang/mlir-clang.cc
> +//      module->dump();
Saw the changes- looks good!

2022-03-02 17:13 UTC, breanna-devore-mcdonald approved these changes
The CI checks can be ignored- the issues are coming from the original repo, not any Codeplay commits

2022-03-03 15:28 UTC, merged

2022-03-04 02:51 UTC, keryell commented on tools/mlir-clang/Lib/clang-mlir.cc
> +    if (ST->getName().contains("class.cl::sycl") ||
In SYCL 2020 the namespace is now `sycl` instead of `cl::sycl`.